### PR TITLE
Remove campaign promo from home page

### PR DESCRIPTION
**Pull request by timbeardshear**

### CODE REVIEW

**Comment by rift137** [comment]
[[Customers] Update policies to allow for different roles and affiliations.](https://trello.com/c/vSpmZ8Th/518-customers-update-policies-to-allow-for-different-roles-and-affiliations)

**Comment by jesilz** [comment]
@rift137 that's a strange comment 😏 

@timbeardshear I'm reviewing this now... we need to get to these faster!

**Comment by jesilz** [comment]
@timbeardshear deploy when ready

**Comment by timbeardshear** [comment]
@jesilz Thanks! 😃

**Pull request merged**
